# Generated by Django 4.2.7 on 2023-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('mail', models.EmailField(max_length=200, verbose_name='Эл. почта')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('date_edit', models.DateTimeField(auto_now=True, verbose_name='Время редактирования')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Детали задачи')),
                ('card_status', models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default=('active', 'Активно'), max_length=50, verbose_name='Текущий статус')),
            ],
        ),
    ]
