# Generated by Django 4.2.7 on 2023-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('task_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default=('new', 'Новая'), max_length=50, verbose_name='Текущий статус')),
                ('date', models.CharField(blank=True, default='yyyy-mm-dd', max_length=10, verbose_name='Сделать до...')),
            ],
        ),
    ]
