# Generated by Django 4.2.7 on 2023-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default=('new', 'New'), max_length=50, verbose_name='Текущий статус'),
        ),
    ]
